version: "3.8"

services:
  fso-phonebook-fullstack:
    image: fso/phonebook-fullstack
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: fso_phonebook_fullstack