name: Deployment pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Set up Node runtime for the app
        uses: actions/setup-node@v3
        with:
          node-version: 18.11.0
      # Split cypress install & tests
      - name: Install dependencies
        uses: cypress-io/github-action@v5
        with:
          runTests: false
      - name: Lint code
        run: npm run lint
      - name: Build
        # env:
        #   REACT_APP_BACKEND_URL: http://localhost:8080
        run: npm run build
      - name: Run E2E tests
        uses: cypress-io/github-action@v5
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DEBUG: '@cypress/github-action'
          NODE_ENV: 'production'
        with:
          install: false
          start: npm run start-prod
          wait-on: 'npx wait-on --timeout 60000 http://localhost:8080'
    
  publish-docker-image:
    runs-on: ubuntu-20.04
    needs: ['test-build']
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event), '#skip') }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: michaelnguyencreative/fso-phonebook-fullstack:latest
  
  deploy-app:
    runs-on: ubuntu-20.04
    needs: ['publish-docker-image']
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event), '#skip') }}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to flyio
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        
  release-tag:
    runs-on: ubuntu-20.04
    needs: ['deploy-app']
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event), '#skip') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version & push tag
        id: release_tag
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          INITIAL_VERSION: '2.0.0'
  
  discord-notify:
    runs-on: ubuntu-20.04
    needs: ['test-build', 'deploy-app', 'publish-docker-image', 'release-tag']
    if: ${{ github.event_name == 'push' && always() }}
    steps:
      - name: Deployment success
        if: ${{ !contains(join(needs.*.result, ','), 'failure') }}
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          username: Michael Nguyen
          description: New Phonebook app is available at https://fso-phonebook-fullstack.fly.dev/
          text: Deployed a new version of phonebook app
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Deployment failure
        if: ${{ contains(join(needs.*.result, ','), 'failure') }}
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: error
          username: Michael Nguyen
          text: Oops! Some jobs have failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    

    