name: Deployment pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Set up Node runtime for the app
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Install dependencies
        run: npm i
      - name: Lint code
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Run E2E tests
        uses: cypress-io/github-action@v5
        with: 
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:3003

  # release_tag:
  #   runs-on: ubuntu-latest
  #   needs: [lint_test_deploy]