name: Deployment pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Set up Node runtime for the app
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - name: Lint code
        run: npm run test
      - name: Build
        run: npm run build

  # release_tag:
  #   runs-on: ubuntu-latest
  #   needs: [lint_test_deploy]