name: Deployment pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Set up Node runtime for the app
        uses: actions/setup-node@v3
        with:
          node-version: 18.11.0
      - name: Install dependencies
        run: npm i
      - name: Lint code
        run: npm run lint
      - name: Build
        env:
          REACT_APP_BACKEND_URL: http://localhost:8080
        run: npm run build
      - name: Run E2E tests
        uses: cypress-io/github-action@v5
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DEBUG: '@cypress/github-action'
          NODE_ENV: 'production'
        with:
          build: npm i -D cypress
          start: npm run start-prod
          wait-on: 'npx wait-on --timeout 60000 http://localhost:8080'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to flyio
        id: deploy_fly
        if: ${{ github.event_name == 'push' && !contains(toJson(github.event), '#skip') }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
        
  release_tag:
    runs-on: ubuntu-latest
    needs: [lint_test_deploy]
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event), '#skip') }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version & push tag
        id: release_tag
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
          INITIAL_VERSION: '2.0.0'
  
  discord_notify:
    runs-on: ubuntu-latest
    needs: [lint_test_deploy, release_tag]
    steps:
      - name: Deployment success
        if: ${{ success() }}
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: info
          username: Michael Nguyen
          description: New Phonebook app is available at https://damp-morning-4577.fly.dev/
          text: Deployed a new version of phonebook app
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Deployment failure
        if: ${{ failure() }}
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          severity: error
          username: Michael Nguyen
          text: Oops! Some jobs have failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    

    