name: Deployment pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3
      - name: Set up Node runtime for the app
        uses: actions/setup-node@v3
        with:
          node-version: 18.11.0
      - name: Install dependencies
        run: npm i
      - name: Lint code
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Run E2E tests
        uses: cypress-io/github-action@v5
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:3001
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to flyio
        if: ${{ github.event_name == "push" }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only
        
  release_tag:
    runs-on: ubuntu-latest
    needs: [lint_test_deploy]
    if: ${{ github.event_name == "push" }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version & push tag
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true

    